name: publish

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          7.x
          8.x
          9.x
    - name: Get Version
      run: echo "VERSION=$(date '+%Y.%m%d')" >> $GITHUB_ENV
    - name: Build
      run: |
        dotnet build -c Release --version-suffix ${{ env.VERSION }}
    - name: Pack
      run: |
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube/DH.NCube.csproj
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCubeNC/DH.NCubeNC.csproj
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube.Swagger/DH.NCube.Swagger.csproj
        #dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube.AdminLTE/DH.NCube.AdminLTE.csproj
        #dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube.ElementUI/DH.NCube.ElementUI.csproj
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube.LayuiAdmin/DH.NCube.LayuiAdmin.csproj
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube.Metronic/DH.NCube.Metronic.csproj
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube.Metronic8/DH.NCube.Metronic8.csproj
        #dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCube.Tabler/DH.NCube.Tabler.csproj

    - name: Publish
      run: |
        #dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/PeiKeSmart/index.json --api-key ${{ github.token }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.chuangchu.net/v3/index.json --api-key ${{ secrets.mynugetKey }}
